name: Deploy to Vercel

on:
  push:
    branches:
      - main # Cambia esto a la rama que deseas desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install # Cambia esto si usas otra herramienta (pnpm, yarn, etc.)

      - name: Build the project
        env:
          STRAPI_HOST: ${{ secrets.STRAPI_HOST }}
          STRAPI_API_KEY: ${{ secrets.STRAPI_API_KEY }}
        run: npm run build # Cambia esto según tu script de build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token=$VERCEL_TOKEN --yes
